export const bangladeshCities = [
  "Dhaka",
  "Chittagong",
  "Sylhet",
  "Rajshahi",
  "Khulna",
  "Barishal",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Narayanganj",
  "Gazipur",
];

export const cityAreas: Record<string, string[]> = {
  Dhaka: [
    "Gulshan",
    "Banani",
    "Dhanmondi",
    "Uttara",
    "Mirpur",
    "Mohammadpur",
    "Badda",
    "Motijheel",
    "Khilgaon",
    "Farmgate",
    "Jatrabari",
    "Paltan",
    "Rampura",
    "Tejgaon",
    "Other",
  ],
  Chittagong: [
    "Agrabad",
    "Halishahar",
    "Khulshi",
    "Nasirabad",
    "Panchlaish",
    "Patenga",
    "Kotwali",
    "Other",
  ],
  Sylhet: [
    "Zindabazar",
    "Amberkhana",
    "Uposhohor",
    "Shibganj",
    "Bandar Bazar",
    "Other",
  ],
  Rajshahi: ["Shaheb Bazar", "Motihar", "Boalia", "Rajpara", "Other"],
  Khulna: ["Sonadanga", "Khalishpur", "Daulatpur", "Boyra", "Other"],
  Barishal: ["Sadar Road", "Rupatali", "Nathullabad", "Other"],
  Rangpur: ["Dhap", "Shapla Chottor", "Carmichael College Area", "Other"],
  Mymensingh: ["Ganginarpar", "Charpara", "Kewatkhali", "Other"],
  Comilla: ["Kandirpar", "Paduar Bazar", "Tomchom Bridge", "Other"],
  Narayanganj: ["Chashara", "Signboard", "Fatullah", "Other"],
  Gazipur: ["Tongi", "Board Bazar", "Joydebpur", "Chowrasta", "Other"],
};
