import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { flexDirection: "column", backgroundColor: "#FFFFFF", padding: 30 },
  header: {
    fontSize: 18,
    marginBottom: 5,
    fontWeight: "bold",
    color: "#1e1e1e",
  },
  subheader: { fontSize: 10, color: "#666666", marginBottom: 2 },
  infoBox: {
    marginTop: 15,
    marginBottom: 15,
    padding: 10,
    backgroundColor: "#f3f4f6",
    borderRadius: 5,
  },
  infoText: { fontSize: 10, color: "#374151", marginBottom: 3 },
  table: {
    display: "flex",
    width: "auto",
    borderStyle: "solid",
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: { flexDirection: "row" },
  tableColHeader: {
    flex: 1,
    borderStyle: "solid",
    borderColor: "#e5e7eb",
    borderBottomColor: "#000",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    backgroundColor: "#4f46e5",
  },
  tableCol: {
    flex: 1,
    borderStyle: "solid",
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCellHeader: {
    margin: 5,
    fontSize: 9,
    fontWeight: "bold",
    color: "#ffffff",
  },
  tableCell: { margin: 5, fontSize: 8, color: "#374151" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 10,
  },
  footerText: { fontSize: 9, color: "#9ca3af" },
});

export interface GenericPdfReportProps {
  title: string;
  generatedBy: string;
  filters?: { label: string; value: string }[];
  columns: string[];
  data: string[][];
}

export const GenericPdfReport = ({
  title,
  generatedBy,
  filters = [],
  columns,
  data,
}: GenericPdfReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View>
        <Text style={styles.header}>Expense Tracker</Text>
        <Text style={styles.header}>{title}</Text>
        <Text style={styles.subheader}>
          Generated Date: {new Date().toLocaleDateString()}
        </Text>
        <Text style={styles.subheader}>Generated By: {generatedBy}</Text>
      </View>

      {filters && filters.length > 0 && (
        <View style={styles.infoBox}>
          {filters.map((f, i) => (
            <Text key={i} style={styles.infoText}>
              <Text style={{ fontWeight: "bold" }}>{f.label}: </Text>
              {f.value}
            </Text>
          ))}
        </View>
      )}

      <View style={styles.table}>
        <View style={styles.tableRow}>
          {columns.map((col, i) => (
            <View key={i} style={styles.tableColHeader}>
              <Text style={styles.tableCellHeader}>{col}</Text>
            </View>
          ))}
        </View>
        {data.map((row, rowIndex) => (
          <View style={styles.tableRow} key={rowIndex}>
            {row.map((cell, cellIndex) => (
              <View key={cellIndex} style={styles.tableCol}>
                <Text style={styles.tableCell}>{cell}</Text>
              </View>
            ))}
          </View>
        ))}
      </View>

      <View style={styles.footer} fixed>
        <Text style={styles.footerText}>Total Records: {data.length}</Text>
        <Text
          style={styles.footerText}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          }
        />
      </View>
    </Page>
  </Document>
);
